'use client'

import type { ReactNode } from 'react'
import ReportNoteValue from '@/app/components/ReportNoteValue'
import type { ReportField } from '@/app/lib/reportTypes'

interface ReportCardData {
  residentName: string
  shiftType: string
  date: string
  professionalSummary: string
  fields: ReportField[]
}

interface ReportCardProps {
  report: ReportCardData
  isExpanded?: boolean
  showDetailedNotes?: boolean
  printMode?: boolean
  printOnly?: boolean
  heading?: string
  footerText?: string
  onToggleDetails?: () => void
  onPrint?: () => void
  onDelete?: () => void
  saveButton?: ReactNode
}

export default function ReportCard({
  report,
  isExpanded = false,
  showDetailedNotes = false,
  printMode = false,
  printOnly = false,
  heading = 'Shift Report',
  footerText,
  onToggleDetails,
  onPrint,
  onDelete,
  saveButton,
}: ReportCardProps) {
  const generatedFooter = footerText ?? `Generated by KingdomCare OS · ${report.date}`

  return (
    <article
      className={[
        'overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm',
        printOnly ? 'print:hidden' : '',
        printMode ? 'print:rounded-none print:border-0 print:shadow-none' : '',
      ]
        .filter(Boolean)
        .join(' ')}
    >
      {/* Header stripe */}
      <div className="border-b border-slate-100 bg-slate-50/60 px-6 py-4">
        <p
          className={[
            'text-[11px] font-bold uppercase tracking-widest text-blue-600',
            printMode ? 'print:text-slate-700' : '',
          ]
            .filter(Boolean)
            .join(' ')}
        >
          {heading}
        </p>
        <h2 className="mt-0.5 text-lg font-bold text-slate-900">{report.residentName}</h2>
        <div className="mt-0.5 flex flex-wrap items-center gap-x-2 gap-y-0.5 text-sm text-slate-500">
          <span className="font-medium text-slate-600">{report.shiftType} Shift</span>
          <span aria-hidden="true">·</span>
          <span>{report.date}</span>
        </div>
      </div>

      {/* Professional summary */}
      <div className="px-6 py-4">
        <div className="rounded-xl bg-blue-50 px-4 py-3.5">
          <p className="mb-1.5 text-[11px] font-bold uppercase tracking-wide text-blue-600">
            Professional Summary
          </p>
          <p className="text-sm leading-relaxed text-slate-700">{report.professionalSummary}</p>
        </div>
      </div>

      {/* Detailed notes */}
      {showDetailedNotes && (
        <div className="border-t border-slate-100 px-6 py-4 space-y-4">
          <p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">
            Detailed Notes
          </p>
          {report.fields.map(({ label, value }) => (
            <div key={label}>
              <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">
                {label}
              </p>
              <ReportNoteValue value={value} />
            </div>
          ))}
          <p className="border-t border-slate-100 pt-3 text-xs italic text-slate-400">
            {generatedFooter}
          </p>
        </div>
      )}

      {/* Footer actions */}
      {(onToggleDetails || onPrint || onDelete) && (
        <div className="flex items-center justify-between gap-3 border-t border-slate-100 px-6 py-3.5 print:hidden">
          {onToggleDetails ? (
            <button
              onClick={onToggleDetails}
              className="text-sm font-semibold text-blue-600 transition-colors hover:text-blue-700"
            >
              {isExpanded ? 'Hide notes' : 'View full notes'}
            </button>
          ) : (
            <div />
          )}

          {(onPrint || onDelete) && (
            <div className="flex items-center gap-4">
              {onPrint && (
                <button
                  onClick={onPrint}
                  className="text-sm font-semibold text-slate-500 transition-colors hover:text-slate-700"
                >
                  Print / PDF
                </button>
              )}
              {onDelete && (
                <button
                  onClick={onDelete}
                  className="text-sm font-semibold text-red-600 transition-colors hover:text-red-700"
                >
                  Delete
                </button>
              )}
            </div>
          )}
        </div>
      )}

      {/* Save button slot */}
      {saveButton && (
        <div className="border-t border-slate-100 px-6 pb-6 pt-4">
          {saveButton}
        </div>
      )}
    </article>
  )
}
